import Head from 'next/head';

export default function MarketplacePage() {
  return (
    <div className="min-h-[calc(100vh-150px)] p-8 bg-creamy-ivory">
      <Head>
        <title>BeeTrace - Credit Marketplace</title>
      </Head>
      <div className="max-w-6xl mx-auto">
        <h1 className="font-heading text-4xl font-bold text-deep-amber mb-8">Pollination & Carbon Credit Marketplace</h1>
        <p className="text-charcoal-grey text-lg mb-4">Discover and trade ecological credits generated by beekeepers.</p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Placeholder for Credit Listings */}
          <div className="bg-white p-6 rounded-lg shadow-md border border-light-grey">
            <h2 className="font-heading text-2xl font-semibold text-olive-green mb-4">Pollination Credit #001</h2>
            <p className="text-dark-grey mb-2">From: Beekeeper XYZ</p>
            <p className="text-dark-grey mb-4">Amount: 100 Pollination Units</p>
            <p className="text-golden-honey font-bold text-xl mb-4">Price: 5 ICP</p>
            <button className="btn-primary w-full">Buy Now</button>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-md border border-light-grey">
            <h2 className="font-heading text-2xl font-semibold text-olive-green mb-4">Carbon Offset #005</h2>
            <p className="text-dark-grey mb-2">From: Apiary ABC</p>
            <p className="text-dark-grey mb-4">Amount: 1 Tonne CO2e</p>
            <p className="text-golden-honey font-bold text-xl mb-4">Price: 15 ICP</p>
            <button className="btn-primary w-full">Buy Now</button>
          </div>
          {/* Add more placeholders as needed */}
        </div>
      </div>
    </div>
  );
}